/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.7).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.TimeEntry;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-08-16T02:49:07.097Z")

@Api(value = "time-entries", description = "the time-entries API")
public interface TimeEntriesApi {

    @ApiOperation(value = "", nickname = "timeEntriesPost", notes = "", tags={ "time-entries", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success"),
        @ApiResponse(code = 400, message = "Invalid entry data.") })
    @RequestMapping(value = "/time-entries",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> timeEntriesPost(@ApiParam(value = "Username, start time, and end time." ,required=true )  @Valid @RequestBody TimeEntry body);


    @ApiOperation(value = "", nickname = "timeEntriesUsernameGet", notes = "", response = List.class, tags={ "time-entries", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = List.class),
        @ApiResponse(code = 404, message = "User with that username not found") })
    @RequestMapping(value = "/time-entries/{username}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<TimeEntry>> timeEntriesUsernameGet(@ApiParam(value = "",required=true) @PathVariable("username") String username);

}
